language: cpp

matrix:
  include:
    - os: linux
      compiler: clang
      sudo: required
      dist: precise
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
            - george-edison55-precise-backports
          packages:
            - cmake
            - cmake-data
            - g++-5
            - clang-3.8
      env:
        - CXXCOMPILER=clang++-3.8 CCOMPILER=clang-3.8
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode7.2
    - os: osx
      osx_image: xcode7.1
    - os: osx
      osx_image: xcode7

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew reinstall cmake ; fi
  - cmake --version
  
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$CXXCOMPILER -DCMAKE_C_COMPILER=$CCOMPILER -DCMAKE_BUILD_TYPE=Release ..
  - make -j4
  - cd tests
  - ctest
